---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reactable)
library(tidyverse)
library(dplyr)
library(sparkline)
library(scales)
library(htmltools)
library(paletteer)
library(reactablefmtr)
library(webshot2)
library(sparkline)
library(formattable)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}


make_color_pal <- function(colors, bias = 1) {
  get_color <- colorRamp(colors, bias = bias)
  function(x) rgb(get_color(x), maxColorValue = 255)
}

good_color <- make_color_pal(c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"), bias = 2)

data <- read_csv("flavors_of_cacao.csv")
names(data)[1] <- "company"
names(data)[5] <- "cocoa_percent"
names(data)[6] <- "location"
names(data)[7] <- "rating"
data$cocoa_percent <- as.numeric(sub("%", "", data$cocoa_percent))

data_first <- data %>%
  mutate(average_rating = mean(rating)) %>%
  group_by(company) %>%
  mutate(average_rating_by_company = mean(rating)) %>%
  filter(n()>10) %>%
  distinct(company, .keep_all = T)
  

data_company <- data %>%
  group_by(company) %>%
  filter(n()>10) %>%
  summarise(cocoa_percent = list(cocoa_percent)) %>%
  mutate(average_rating = data_first$average_rating, 
         average_rating_by_company = data_first$average_rating_by_company,
         location = data_first$location)


data_company$average_rating_by_company <- round(data_company$average_rating_by_company,2)
data_company$average_rating <- round(data_company$average_rating, 2)

a <-reactable(
  data_company %>% dplyr::select(company, location, average_rating_by_company, cocoa_percent) %>% arrange(desc(average_rating_by_company)),
  style = list(fontFamily = 'Menlo',
                       fontSize = '14px'),
  pagination = FALSE,
  compact = TRUE,
  borderless = FALSE,
  striped = FALSE,
  fullWidth = FALSE,
  defaultColDef = colDef(
    align = "center",
    minWidth = 100
  ),
  theme = reactableTheme(
    headerStyle = list(
      "&:hover[aria-sort]" = list(background = "hsl(0, 0%, 96%)"),
      "&[aria-sort='ascending'], &[aria-sort='descending']" = list(background = "hsl(0, 0%, 96%)"),
      borderColor = "#555"
    )
  ),
  columns = list(
    average_rating_by_company = colDef(
      name = "Rating by Company",
      minWidth = 100,
      style = function(value) {
        value
        normalized <- (value - min(data_company$average_rating_by_company)) / (max(data_company$average_rating_by_company) - min(data_company$average_rating_by_company))
        color <- good_color(normalized)
        list(background = color)
      }),
        cocoa_percent = colDef(
          name = "Cacao % in products",
          minWidth = 200,
          cell = react_sparkbar(
            data_company,
            height = 35,
            fill_color  = "#4c9b9b",
            statline_color = "orange",
            statline_label_color = "orange",
            statline_label_size = "1.1em",
            statline = "mean"),
          class = "border-left"),
    company = colDef(
      name = "Company",
      minWidth = 200,
      align = "left",
      style = list(fontFamily = 'Arial',
                       fontSize = '14px')
    ),
    location = colDef(
      name = "Location",
      minWidth = 120,
      style = list(fontFamily = 'Arial',
                       fontSize = '14px')
    )
    ))


div(
  class = "salary",
  div(
    class = "title",
    h2("Analysis of Cacao Manufacturers"),
    "Which companies produce better cacao?"
  ),
  a,
  tags$span(style = "color:#C8C8C8", "TABLE: @muhammetozkrc | Source: Flavors of Cacao")
)

tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")

# save_reactable("tidy-tuesday.html", "tidy-tuesday.png")


```

```{css, echo=FALSE, warning=FALSE, message=FALSE}
.title h2 {
  font-family: "Fira Mono";
  font-size: 20px;
  font-weight: 600;
  margin-bottom: 10px;
  padding-bottom: 10px;
  border-bottom: solid 1px #d3d3d3;
}

.border-left {
  border-left: 2px solid #555;
}

/* Align header text to the bottom */
.header,
.group-header {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}

.header {
  border-bottom-color: #555;
  font-size: 13px;
  font-weight: 400;
  text-transform: uppercase;
}
```

